### ISSUE TITLE
Checklist for milestone 3

### ISSUE THREAD

**Issue by nullstyle** [stellar/go-horizon#54]
- [x] Horizon API
  - [x] Orderbook and Offers
    - [x] order book summary view tests
    - [x] fix "offers for account" bug
  - [x] Effects Import
    - [x] Interpret path payments, manage offers, and create passive offer operations
      for "trade" effects
    - [x] Import effects from manage offer operations
    - [x] Import effects from create passive offer operations
    - [x] Fill out effects that occur due to Set Options effects
    - [x] Add "raw xdr" storage to transaction entries in history db
  - [x] Pathfinding
    - [x] design endpoint
    - [x] Port ruby prototype to go
    - [x] Write test suite
  - [x] Trading API
    - [x] Add "trades" endpoint
